using System.ComponentModel;

namespace YoutubeSnoop.Enums
{
    public enum CountryCode
    {
        [Description("Andorra")] Ad,
        [Description("United Arab Emirates")] Ae,
        [Description("Afghanistan")] Af,
        [Description("Antigua and Barbuda")] Ag,
        [Description("Anguilla")] Ai,
        [Description("Albania")] Al,
        [Description("Armenia")] Am,
        [Description("Angola")] Ao,
        [Description("Antarctica")] Aq,
        [Description("Argentina")] Ar,
        [Description("American Samoa")] As,
        [Description("Austria")] At,
        [Description("Australia")] Au,
        [Description("Aruba")] Aw,
        [Description("Åland Islands")] Ax,
        [Description("Azerbaijan")] Az,
        [Description("Bosnia and Herzegovina")] Ba,
        [Description("Barbados")] Bb,
        [Description("Bangladesh")] Bd,
        [Description("Belgium")] Be,
        [Description("Burkina Faso")] Bf,
        [Description("Bulgaria")] Bg,
        [Description("Bahrain")] Bh,
        [Description("Burundi")] Bi,
        [Description("Benin")] Bj,
        [Description("Saint Barthélemy")] Bl,
        [Description("Bermuda")] Bm,
        [Description("Brunei Darussalam")] Bn,
        [Description("Bolivia, Plurinational State of")] Bo,
        [Description("Bonaire, Sint Eustatius and Saba")] Bq,
        [Description("Brazil")] Br,
        [Description("Bahamas")] Bs,
        [Description("Bhutan")] Bt,
        [Description("Bouvet Island")] Bv,
        [Description("Botswana")] Bw,
        [Description("Belarus")] By,
        [Description("Belize")] Bz,
        [Description("Canada")] Ca,
        [Description("Cocos (Keeling) Islands")] Cc,
        [Description("Congo, the Democratic Republic of the")] Cd,
        [Description("Central African Republic")] Cf,
        [Description("Congo")] Cg,
        [Description("Switzerland")] Ch,
        [Description("Côte d'Ivoire")] Ci,
        [Description("Cook Islands")] Ck,
        [Description("Chile")] Cl,
        [Description("Cameroon")] Cm,
        [Description("China")] Cn,
        [Description("Colombia")] Co,
        [Description("Costa Rica")] Cr,
        [Description("Cuba")] Cu,
        [Description("Cabo Verde")] Cv,
        [Description("Curaçao")] Cw,
        [Description("Christmas Island")] Cx,
        [Description("Cyprus")] Cy,
        [Description("Czechia")] Cz,
        [Description("Germany")] De,
        [Description("Djibouti")] Dj,
        [Description("Denmark")] Dk,
        [Description("Dominica")] Dm,
        [Description("Dominican Republic")] Do,
        [Description("Algeria")] Dz,
        [Description("Ecuador")] Ec,
        [Description("Estonia")] Ee,
        [Description("Egypt")] Eg,
        [Description("Western Sahara")] Eh,
        [Description("Eritrea")] Er,
        [Description("Spain")] Es,
        [Description("Ethiopia")] Et,
        [Description("Finland")] Fi,
        [Description("Fiji")] Fj,
        [Description("Falkland Islands (Malvinas)")] Fk,
        [Description("Micronesia, Federated States of")] Fm,
        [Description("Faroe Islands")] Fo,
        [Description("France")] Fr,
        [Description("Gabon")] Ga,
        [Description("United Kingdom of Great Britain and Northern Ireland")] Gb,
        [Description("Grenada")] Gd,
        [Description("Georgia")] Ge,
        [Description("French Guiana")] Gf,
        [Description("Guernsey")] Gg,
        [Description("Ghana")] Gh,
        [Description("Gibraltar")] Gi,
        [Description("Greenland")] Gl,
        [Description("Gambia")] Gm,
        [Description("Guinea")] Gn,
        [Description("Guadeloupe")] Gp,
        [Description("Equatorial Guinea")] Gq,
        [Description("Greece")] Gr,
        [Description("South Georgia and the South Sandwich Islands")] Gs,
        [Description("Guatemala")] Gt,
        [Description("Guam")] Gu,
        [Description("Guinea-Bissau")] Gw,
        [Description("Guyana")] Gy,
        [Description("Hong Kong")] Hk,
        [Description("Heard Island and McDonald Islands")] Hm,
        [Description("Honduras")] Hn,
        [Description("Croatia")] Hr,
        [Description("Haiti")] Ht,
        [Description("Hungary")] Hu,
        [Description("Indonesia")] Id,
        [Description("Ireland")] Ie,
        [Description("Israel")] Il,
        [Description("Isle of Man")] Im,
        [Description("India")] In,
        [Description("British Indian Ocean Territory")] Io,
        [Description("Iraq")] Iq,
        [Description("Iran, Islamic Republic of")] Ir,
        [Description("Iceland")] Is,
        [Description("Italy")] It,
        [Description("Jersey")] Je,
        [Description("Jamaica")] Jm,
        [Description("Jordan")] Jo,
        [Description("Japan")] Jp,
        [Description("Kenya")] Ke,
        [Description("Kyrgyzstan")] Kg,
        [Description("Cambodia")] Kh,
        [Description("Kiribati")] Ki,
        [Description("Comoros")] Km,
        [Description("Saint Kitts and Nevis")] Kn,
        [Description("Korea, Democratic People's Republic of")] Kp,
        [Description("Korea, Republic of")] Kr,
        [Description("Kuwait")] Kw,
        [Description("Cayman Islands")] Ky,
        [Description("Kazakhstan")] Kz,
        [Description("Lao People's Democratic Republic")] La,
        [Description("Lebanon")] Lb,
        [Description("Saint Lucia")] Lc,
        [Description("Liechtenstein")] Li,
        [Description("Sri Lanka")] Lk,
        [Description("Liberia")] Lr,
        [Description("Lesotho")] Ls,
        [Description("Lithuania")] Lt,
        [Description("Luxembourg")] Lu,
        [Description("Latvia")] Lv,
        [Description("Libya")] Ly,
        [Description("Morocco")] Ma,
        [Description("Monaco")] Mc,
        [Description("Moldova, Republic of")] Md,
        [Description("Montenegro")] Me,
        [Description("Saint Martin (French part)")] Mf,
        [Description("Madagascar")] Mg,
        [Description("Marshall Islands")] Mh,
        [Description("Macedonia, the former Yugoslav Republic of")] Mk,
        [Description("Mali")] Ml,
        [Description("Myanmar")] Mm,
        [Description("Mongolia")] Mn,
        [Description("Macao")] Mo,
        [Description("Northern Mariana Islands")] Mp,
        [Description("Martinique")] Mq,
        [Description("Mauritania")] Mr,
        [Description("Montserrat")] Ms,
        [Description("Malta")] Mt,
        [Description("Mauritius")] Mu,
        [Description("Maldives")] Mv,
        [Description("Malawi")] Mw,
        [Description("Mexico")] Mx,
        [Description("Malaysia")] My,
        [Description("Mozambique")] Mz,
        [Description("Namibia")] Na,
        [Description("New Caledonia")] Nc,
        [Description("Niger")] Ne,
        [Description("Norfolk Island")] Nf,
        [Description("Nigeria")] Ng,
        [Description("Nicaragua")] Ni,
        [Description("Netherlands")] Nl,
        [Description("Norway")] No,
        [Description("Nepal")] Np,
        [Description("Nauru")] Nr,
        [Description("Niue")] Nu,
        [Description("New Zealand")] Nz,
        [Description("Oman")] Om,
        [Description("Panama")] Pa,
        [Description("Peru")] Pe,
        [Description("French Polynesia")] Pf,
        [Description("Papua New Guinea")] Pg,
        [Description("Philippines")] Ph,
        [Description("Pakistan")] Pk,
        [Description("Poland")] Pl,
        [Description("Saint Pierre and Miquelon")] Pm,
        [Description("Pitcairn")] Pn,
        [Description("Puerto Rico")] Pr,
        [Description("Palestine, State of")] Ps,
        [Description("Portugal")] Pt,
        [Description("Palau")] Pw,
        [Description("Paraguay")] Py,
        [Description("Qatar")] Qa,
        [Description("Réunion")] Re,
        [Description("Romania")] Ro,
        [Description("Serbia")] Rs,
        [Description("Russian Federation")] Ru,
        [Description("Rwanda")] Rw,
        [Description("Saudi Arabia")] Sa,
        [Description("Solomon Islands")] Sb,
        [Description("Seychelles")] Sc,
        [Description("Sudan")] Sd,
        [Description("Sweden")] Se,
        [Description("Singapore")] Sg,
        [Description("Saint Helena, Ascension and Tristan da Cunha")] Sh,
        [Description("Slovenia")] Si,
        [Description("Svalbard and Jan Mayen")] Sj,
        [Description("Slovakia")] Sk,
        [Description("Sierra Leone")] Sl,
        [Description("San Marino")] Sm,
        [Description("Senegal")] Sn,
        [Description("Somalia")] So,
        [Description("Suriname")] Sr,
        [Description("South Sudan")] Ss,
        [Description("Sao Tome and Principe")] St,
        [Description("El Salvador")] Sv,
        [Description("Sint Maarten (Dutch part)")] Sx,
        [Description("Syrian Arab Republic")] Sy,
        [Description("Swaziland")] Sz,
        [Description("Turks and Caicos Islands")] Tc,
        [Description("Chad")] Td,
        [Description("French Southern Territories")] Tf,
        [Description("Togo")] Tg,
        [Description("Thailand")] Th,
        [Description("Tajikistan")] Tj,
        [Description("Tokelau")] Tk,
        [Description("Timor-Leste")] Tl,
        [Description("Turkmenistan")] Tm,
        [Description("Tunisia")] Tn,
        [Description("Tonga")] To,
        [Description("Turkey")] Tr,
        [Description("Trinidad and Tobago")] Tt,
        [Description("Tuvalu")] Tv,
        [Description("Taiwan, Province of China")] Tw,
        [Description("Tanzania, United Republic of")] Tz,
        [Description("Ukraine")] Ua,
        [Description("Uganda")] Ug,
        [Description("United States Minor Outlying Islands")] Um,
        [Description("United States of America")] Us,
        [Description("Uruguay")] Uy,
        [Description("Uzbekistan")] Uz,
        [Description("Holy See")] Va,
        [Description("Saint Vincent and the Grenadines")] Vc,
        [Description("Venezuela, Bolivarian Republic of")] Ve,
        [Description("Virgin Islands, British")] Vg,
        [Description("Virgin Islands, U.S.")] Vi,
        [Description("Viet Nam")] Vn,
        [Description("Vanuatu")] Vu,
        [Description("Wallis and Futuna")] Wf,
        [Description("Samoa")] Ws,
        [Description("Yemen")] Ye,
        [Description("Mayotte")] Yt,
        [Description("South Africa")] Za,
        [Description("Zambia")] Zm,
        [Description("Zimbabwe")] Zw
    }
}
