using System.ComponentModel;

namespace YoutubeSnoop.Enums
{
    public enum LanguageCode
    {
        [Description("(Afan) Oromo")] Om,
        [Description("Abkhazian")] Ab,
        [Description("Afar")] Aa,
        [Description("Afrikaans")] Af,
        [Description("Albanian")] Sq,
        [Description("Amharic")] Am,
        [Description("Arabic")] Ar,
        [Description("Armenian")] Hy,
        [Description("Assamese")] As,
        [Description("Aymara")] Ay,
        [Description("Azerbaijani")] Az,
        [Description("Bashkir")] Ba,
        [Description("Basque")] Eu,
        [Description("Bengali")] Bn,
        [Description("Bhutani")] Dz,
        [Description("Bihari")] Bh,
        [Description("Bislama")] Bi,
        [Description("Breton")] Br,
        [Description("Bulgarian")] Bg,
        [Description("Burmese")] My,
        [Description("Byelorussian")] Be,
        [Description("Cambodian")] Km,
        [Description("Catalan")] Ca,
        [Description("Chinese")] Zh,
        [Description("Corsican")] Co,
        [Description("Croatian")] Hr,
        [Description("Czech")] Cs,
        [Description("Danish")] Da,
        [Description("Dutch")] Nl,
        [Description("English")] En,
        [Description("Esperanto")] Eo,
        [Description("Estonian")] Et,
        [Description("Faeroese")] Fo,
        [Description("Fiji")] Fj,
        [Description("Finnish")] Fi,
        [Description("French")] Fr,
        [Description("Frisian")] Fy,
        [Description("Galician")] Gl,
        [Description("Georgian")] Ka,
        [Description("German")] De,
        [Description("Greek")] El,
        [Description("Greenlandic")] Kl,
        [Description("Guarani")] Gn,
        [Description("Gujarati")] Gu,
        [Description("Hausa")] Ha,
        [Description("Hebrew (former iw)")] He,
        [Description("Hindi")] Hi,
        [Description("Hungarian")] Hu,
        [Description("Icelandic")] Is,
        [Description("Indonesian (former in)")] Id,
        [Description("Interlingua")] Ia,
        [Description("Interlingue")] Ie,
        [Description("Inupiak")] Ik,
        [Description("Inuktitut (Eskimo)")] Iu,
        [Description("Irish")] Ga,
        [Description("Italian")] It,
        [Description("Japanese")] Ja,
        [Description("Javanese")] Jw,
        [Description("Kannada")] Kn,
        [Description("Kashmiri")] Ks,
        [Description("Kazakh")] Kk,
        [Description("Kinyarwanda")] Rw,
        [Description("Kirghiz")] Ky,
        [Description("Kirundi")] Rn,
        [Description("Korean")] Ko,
        [Description("Kurdish")] Ku,
        [Description("Laothian")] Lo,
        [Description("Latin")] La,
        [Description("Latvian, Lettish")] Lv,
        [Description("Lingala")] Ln,
        [Description("Lithuanian")] Lt,
        [Description("Macedonian")] Mk,
        [Description("Malagasy")] Mg,
        [Description("Malay")] Ms,
        [Description("Malayalam")] Ml,
        [Description("Maltese")] Mt,
        [Description("Maori")] Mi,
        [Description("Marathi")] Mr,
        [Description("Moldavian")] Mo,
        [Description("Mongolian")] Mn,
        [Description("Nauru")] Na,
        [Description("Nepali")] Ne,
        [Description("Norwegian")] No,
        [Description("Occitan")] Oc,
        [Description("Oriya")] Or,
        [Description("Pashto, Pushto")] Ps,
        [Description("Persian")] Fa,
        [Description("Polish")] Pl,
        [Description("Portuguese")] Pt,
        [Description("Punjabi")] Pa,
        [Description("Quechua")] Qu,
        [Description("Rhaeto-Romance")] Rm,
        [Description("Romanian")] Ro,
        [Description("Russian")] Ru,
        [Description("Samoan")] Sm,
        [Description("Sangro")] Sg,
        [Description("Sanskrit")] Sa,
        [Description("Scots Gaelic")] Gd,
        [Description("Serbian")] Sr,
        [Description("Serbo-Croatian")] Sh,
        [Description("Sesotho")] St,
        [Description("Setswana")] Tn,
        [Description("Shona")] Sn,
        [Description("Sindhi")] Sd,
        [Description("Singhalese")] Si,
        [Description("Siswati")] Ss,
        [Description("Slovak")] Sk,
        [Description("Slovenian")] Sl,
        [Description("Somali")] So,
        [Description("Spanish")] Es,
        [Description("Sudanese")] Su,
        [Description("Swahili")] Sw,
        [Description("Swedish")] Sv,
        [Description("Tagalog")] Tl,
        [Description("Tajik")] Tg,
        [Description("Tamil")] Ta,
        [Description("Tatar")] Tt,
        [Description("Tegulu")] Te,
        [Description("Thai")] Th,
        [Description("Tibetan")] Bo,
        [Description("Tigrinya")] Ti,
        [Description("Tonga")] To,
        [Description("Tsonga")] Ts,
        [Description("Turkish")] Tr,
        [Description("Turkmen")] Tk,
        [Description("Twi")] Tw,
        [Description("Uigur")] Ug,
        [Description("Ukrainian")] Uk,
        [Description("Urdu")] Ur,
        [Description("Uzbek")] Uz,
        [Description("Vietnamese")] Vi,
        [Description("Volapuk")] Vo,
        [Description("Welch")] Cy,
        [Description("Wolof")] Wo,
        [Description("Xhosa")] Xh,
        [Description("Yiddish (former ji)")] Yi,
        [Description("Yoruba")] Yo,
        [Description("Zhuang")] Za,
        [Description("Zulu")] Zu
    }
}